# Generated by Django 3.1.2 on 2020-10-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fumbles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DecimalField(decimal_places=5, max_digits=10)),
                ('name', models.CharField(max_length=30)),
                ('ff', models.DecimalField(decimal_places=5, max_digits=10)),
                ('fr', models.DecimalField(decimal_places=5, max_digits=10)),
                ('fr_td', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Passing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DecimalField(decimal_places=5, max_digits=10)),
                ('name', models.CharField(max_length=30)),
                ('pass_yds', models.DecimalField(decimal_places=5, max_digits=10)),
                ('yds_att', models.DecimalField(decimal_places=5, max_digits=10)),
                ('att', models.DecimalField(decimal_places=5, max_digits=10)),
                ('cmp', models.DecimalField(decimal_places=5, max_digits=10)),
                ('cmp_percent', models.DecimalField(decimal_places=5, max_digits=10)),
                ('td', models.DecimalField(decimal_places=5, max_digits=10)),
                ('int', models.DecimalField(decimal_places=5, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=5, max_digits=10)),
                ('one_st', models.DecimalField(decimal_places=5, max_digits=10)),
                ('one_st_percent', models.DecimalField(decimal_places=5, max_digits=10)),
                ('twentyplus', models.DecimalField(decimal_places=5, max_digits=10)),
                ('fourtyplus', models.DecimalField(decimal_places=5, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=5, max_digits=10)),
                ('sck', models.DecimalField(decimal_places=5, max_digits=10)),
                ('scky', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DecimalField(decimal_places=5, max_digits=10)),
                ('name', models.CharField(max_length=30)),
                ('rec', models.DecimalField(decimal_places=5, max_digits=10)),
                ('yds', models.DecimalField(decimal_places=5, max_digits=10)),
                ('td', models.DecimalField(decimal_places=5, max_digits=10)),
                ('twentyplus', models.DecimalField(decimal_places=5, max_digits=10)),
                ('fourtyplus', models.DecimalField(decimal_places=5, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=5, max_digits=10)),
                ('rec_1st', models.DecimalField(decimal_places=5, max_digits=10)),
                ('one_st_percent', models.DecimalField(decimal_places=5, max_digits=10)),
                ('rec_fum', models.DecimalField(decimal_places=5, max_digits=10)),
                ('rec_yac_r', models.DecimalField(decimal_places=5, max_digits=10)),
                ('tgts', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rushing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DecimalField(decimal_places=5, max_digits=10)),
                ('name', models.CharField(max_length=30)),
                ('rush_yds', models.DecimalField(decimal_places=5, max_digits=10)),
                ('att', models.DecimalField(decimal_places=5, max_digits=10)),
                ('td', models.DecimalField(decimal_places=5, max_digits=10)),
                ('twentyplus', models.DecimalField(decimal_places=5, max_digits=10)),
                ('fourtyplus', models.DecimalField(decimal_places=5, max_digits=10)),
                ('rush_one_st', models.DecimalField(decimal_places=5, max_digits=10)),
                ('rush_one_st_percent', models.DecimalField(decimal_places=5, max_digits=10)),
                ('rush_fum', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tackles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DecimalField(decimal_places=5, max_digits=10)),
                ('name', models.CharField(max_length=30)),
                ('comb', models.DecimalField(decimal_places=5, max_digits=10)),
                ('asst', models.DecimalField(decimal_places=5, max_digits=10)),
                ('solo', models.DecimalField(decimal_places=5, max_digits=10)),
                ('sck', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
    ]
